name: SISPS-EXP-SOC
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - regex
  - openpyxl
  - tabulate
  - pip
  - pip:
      - duration
      - darkdetect
