name: Jupyter Notebook Execute

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - "Notebook/**"
      - "Data/**"
      - ".github/workflows/notebook.yml"

env:
  REPO_OWNER: LawrenceStanton

jobs:
  main:
    name: Execute Notebook/main.ipynb
    runs-on: macos-13 # 14GB RAM required

    timeout-minutes: 20

    defaults:
      run:
        shell: bash -el {0} # Required by conda-incubator/setup-miniconda

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{env.REPO_OWNER}}/SISPS-EXP-SOC

      - name: Set up Anaconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ./.conda
          environment-file: Notebook/environment.yml
          python-version: 3.11
          auto-activate-base: false

      - name: Conda Info
        run: |
          conda info
          conda list

      - name: Install Jupyter within Conda Kernel
        run: |
          conda activate ./.conda
          conda install jupyter
          jupyter kernelspec install --user ./.conda --name .conda
          jupyter kernelspec list

      - name: Execute Jupyter Notebooks
        run: |
          jupyter nbconvert --to notebook --execute --inplace Notebook/main.ipynb
          jupyter nbconvert --to notebook --execute --inplace Notebook/concentrationPlots.ipynb
          jupyter nbconvert --to html Notebook/main.ipynb
          jupyter nbconvert --to markdown Notebook/main.ipynb
          jupyter nbconvert --to html Notebook/concentrationPlots.ipynb
          jupyter nbconvert --to markdown Notebook/concentrationPlots.ipynb

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: Notebook Outputs
          path: |
            Notebook/
            Plots/
            Data/

      - name: Upload PGF Plots
        uses: actions/upload-artifact@v4
        with:
          name: PGF Plots
          path: Plots/Latex/

      - name: Write Notebook as Job Summary
        run: |
          cat Notebook/main.md >> $GITHUB_STEP_SUMMARY
          cat Notebook/concentrationPlots.md >> $GITHUB_STEP_SUMMARY
